### ISSUE TITLE
Toggle outlet power as an "do" action?

### ISSUE THREAD

**Issue by sifotes** [robertvorthman/smart-plug-power-monitor#2]
Is it possible to cut the power to the plugged in appliance as an action?
For example, if the power usage drops below a certain level, toggle the outlet then turn it back on. 

I like the project and think that I can adapt the rest of it.

**Comment by robertvorthman** [comment]
Include the [fx-hs100-api](https://www.npmjs.com/package/fx-hs100-api) and then you could do ```plug.setPowerState(true);```

**Comment by sifotes** [comment]
Fantastic, thank you!
