### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by rgerr** [robertvorthman/smart-plug-power-monitor#3]
Hi,

How can I install this node?

**Comment by robertvorthman** [comment]
Try this:
https://nodejs.org/en/download/package-manager/

**Comment by rgerr** [comment]
Thanks! I managed to install it anyway, I've adjusted the index.js as described. However, do I need to remove the comments? 

For example, do I need to remove the bold text in bold?

  smartPlugIP: "", **//REQUIRED example: "192.168.1.5"**

**Comment by robertvorthman** [comment]
You can leave the comments.  Only the non-commented code matters.

**Comment by rgerr** [comment]
Can’t seem to make it work. I installed the node via sudo npm install https://github.com/robertvorthman/smart-plug-power-monitor, adjusted the index.js (only IP and IFTTT Maker Channel) but IFTTT does not receive a message from the node unfortunatly. Could you possibly help me sort this out?

**Comment by robertvorthman** [comment]
Please copy and paste your code for me to see, thanks.

**Comment by rgerr** [comment]
`'use strict';

//TODO update documentation, kwh event data, ifttt ingredient, minRuntimeForCooldownSeconds
// add money estimate

const Hs100Api = require('hs100-api'); //Smart Plug, for monitoring power usage
const IFTTTmaker = require('node-ifttt-maker'); //IFTTT, for sending notifications

class SmartPlugPowerMonitor {
    constructor(options) {

        this.config = {
          smartPlugIP: "192.168.1.xx", //REQUIRED example: "192.168.1.5"
          iftttMakerChannelKey: "https://maker.ifttt.com/use/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", //from https://ifttt.com/maker
          pollIntervalSeconds: 30, //how often to check wattage
          networkRetryIntervalSeconds: 120, //how often to poll if the smart plug IP address is not reachable
          startEventName: 'appliance-started', //IFTTT maker event name
          endEventName: 'appliance-completed', //IFTTT maker event name
          wattsThreshold: 1, //wattage above this value will trigger start event after startTimeWindowSeconds
          startTimeWindowSeconds: 5, //if wattage is exceeded for this period, appliance is considered started
          endTimeWindowSeconds: 30, //if wattage is below threshold for this entire duration, appliance is considered completed running
          cooldownPeriodSeconds: 30, //wait this long after end event before responding to subsequent start events, set to same as poll interval if no cooldown is needed
          minRuntimeForCooldownSeconds: 60, //minimum runtime for cooldown period to engage.  If appliance ends earlier, start polling at usual interval after end instead of waiting for cooldown period
          kwhPrice: 0.12, //price of electricity, to calculate usage cost in IFTTT notification/event callback
          pollingCallback: (powerConsumption)=>{}, //returns the power consumption data on every polling interval
          eventCallback: (event, data)=>{} //called when appliance starts and stops
        };

        Object.assign(this.config, options);

        this.timer;
        this.applianceRunning = false;
        this.elapsedRuntime = 0;
        this.overWattsThresholdStartTime;
        this.underWattsThresholdStartTime;
        this.startKwh;

        this.lastEndTime;


        //check for required options
        this.valid = true;
        if (!this.config.smartPlugIP || typeof this.config.smartPlugIP !== 'string') {
          this.valid = false;
          throw new Error('smartPlugIP (string) is missing from options.  Provide the IP Address of your TP-Link HS110.');
        }else{
          this.smartPlug = new Hs100Api({host: this.config.smartPlugIP});
        }

        if (this.config.iftttMakerChannelKey && typeof this.config.iftttMakerChannelKey == 'string') {
          this.iftttMakerChannel = new IFTTTmaker(this.config.iftttMakerChannelKey);
        }
    }

    start(){
      if(!this.valid){
        throw new Error('Unable to start listening due to invalid configuration options.');
      }else{
        this.poll();

      }
    }

    stop(){
    }

    poll(){
      let self = this;
      try{
        this.smartPlug.getConsumption()
          .then(function(smartPlugData){
            let consumptionData = smartPlugData.get_realtime;
            consumptionData.timestamp = new Date().getTime();
            self.config.pollingCallback(consumptionData);
            self.evaluatePowerUsage(consumptionData);
          })
          .catch(function(err){
            //smart plug unreachable
            self.config.eventCallback('Smart plug IP address unreachable', err);
            self.timer = setTimeout(()=>{self.poll()}, self.config.networkRetryIntervalSeconds*1000);
          });
      } catch(e){
        self.config.eventCallback('Error connecting to switch', e);
      }

    }

    evaluatePowerUsage(consumptionData){

      var wattage = consumptionData.power;

      var now = new Date();
      var applianceJustFinished = false;
      //if above wattage threshold
      if(wattage > this.config.wattsThreshold){
        //reset under watts time
        this.underWattsThresholdStartTime = null;
        //record start time of watts exceeded
        if(!this.overWattsThresholdStartTime){
          this.overWattsThresholdStartTime = new Date();
          this.startKwh = consumptionData.total;
        }



        this.elapsedRuntime = now - this.overWattsThresholdStartTime;

        //detect if appliance running for longer than start time window
        if(!this.applianceRunning && this.elapsedRuntime > this.config.startTimeWindowSeconds * 1000){
          //appliance started
          this.applianceRunning = true;
          this.sendNotification(this.config.startEventName);
        }

      }else if(this.applianceRunning){
        //below watts threshold and appliance running
        if(!this.underWattsThresholdStartTime){
          this.underWattsThresholdStartTime = new Date();
        }

        //elapsed time of watts not exceeded
        var elapsed = now - this.underWattsThresholdStartTime;
        if(elapsed > this.config.endTimeWindowSeconds * 1000){
          //appliance completed
          this.applianceRunning = false;
          var runtime = this.underWattsThresholdStartTime - this.overWattsThresholdStartTime;
          var kwh = consumptionData.total - this.startKwh;
          this.sendNotification(this.config.endEventName, {
            runtime: runtime,
            kwh: kwh,
            cost: kwh * this.config.kwhPrice
          });
          this.lastEndTime = now;
          //reset start time
          this.overWattsThresholdStartTime = null;
        }

      }

      if(this.lastEndTime == now && runtime > this.config.minRuntimeForCooldownSeconds){
        //if appliance running just ended, poll wattage after cooldown period
        setTimeout(()=>{this.poll()}, this.config.cooldownPeriodSeconds*1000);
      }else{
        //otherwise poll at usual polling interval
        setTimeout(()=>{this.poll()}, this.config.pollIntervalSeconds*1000);
      }

    }

    sendNotification(eventName, data){
      this.config.eventCallback(eventName, data);


      var self = this;

      if(this.iftttMakerChannel){

        var params = {};

        if(data && typeof data.runtime != 'undefined'){
          params.value1 = this.toPrettyTime(data.runtime);
          params.value2 = data.kwh.toFixed(3);
          params.value3 = "$"+data.cost.toFixed(2);
        }

        this.iftttMakerChannel.request({
            event: eventName,
            method: 'GET',
            params: params
        }, function (err) {
            if (err) {
              self.config.eventCallback('Failed to send IFTTT notification', err);
            } else {
              //Sent IFTTT notification
            }
        });
      }



    }

    toPrettyTime(milliseconds) {
      var seconds = milliseconds/1000;
      var h = Math.floor(seconds / 3600);
      var m = Math.floor(seconds % 3600 / 60);
      var s = Math.floor(seconds % 3600 % 60);
      var prettyString = (h > 0 ? h + "hr " + (m < 10 ? "0" : "") : "") + m + "m";
      if(h == 0) //add seconds if less than 1 hour
        prettyString += " "+ (s < 10 ? "0" : "") + s+"s";

      return prettyString;
    }

}



module.exports = SmartPlugPowerMonitor;`

**Comment by robertvorthman** [comment]
Installing with ```npm install``` is correct, this should create a node_modules folder in your current directory, but then you should not edit anything inside node_modules.  Instead create another .js file next to the node_modules directory.  The first line of this .js file will use a require statement to import the smart-plug-power-monitor from the node_modules directory into your code.
```js
var SmartPlugPowerMonitor = require("smart-plug-power-monitor");

var smartPlugPowerMonitor = new SmartPlugPowerMonitor({
  smartPlugIP: "192.168.1.xxx",
  pollIntervalSeconds: 1,
  pollingCallback: function(powerConsumption){
    console.log(powerConsumption.power, powerConsumption.timestamp);
  }
});
smartPlugPowerMonitor.start();
```

If you put the code above into a file called index.js, replace your IP address, then run ```node index.js``` you should see log statements of your appliance's wattage.  Once you get that working you can add IFTTT.

**Comment by rgerr** [comment]
0 1520689379344
0 1520689380384
0 1520689381425
0 1520689382463
0 1520689383508
0 1520689384542
0 1520689385586
0 1520689386621
0 1520689387666

This is the output, is that correct? It continues to give similar output and updates every second or so.

If it is correct, where do I add the IFTTT maker link?

**Comment by robertvorthman** [comment]
Yay! It works.  Yes that output is correct.  How about you plug something into the smart plug like a phone charger or lamp to make sure the 0 changes to anything above 0 to make sure you are getting a wattage measurement.  For a super large wattage reading plug in something with a heating element or motor like a coffee maker, toaster or blender.

The second parameter is the timestamp.  You could change the log statement to this to make more sense of your measurement:

```js
console.log("Wattage:", powerConsumption.power, "DateTime:", new Date(powerConsumption.timestamp));
```
Look at these examples for where to add the IFTTT key.
https://github.com/robertvorthman/smart-plug-power-monitor#example
https://github.com/robertvorthman/smart-plug-power-monitor#all-options

Get your maker key from here:
https://ifttt.com/services/maker_webhooks/settings

**Comment by rgerr** [comment]
Think I'm nearly there. I saved a new index.js in /node_modules/ and run the script with sudo node /home/pi/node_modules/index.js

After that, I see the logging as mentioned before.

This is the index.js I created:

`var SmartPlugPowerMonitor = require("smart-plug-power-monitor");

var smartPlugPowerMonitor = new SmartPlugPowerMonitor({
  smartPlugIP: "192.168.1.23",
  iftttMakerChannelKey: "https://maker.ifttt.com/use/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  endEventName: 'appliance-completed',
  wattsThreshold: 1,
  pollIntervalSeconds: 5,
  pollingCallback: function(powerConsumption){
    console.log("Wattage:", powerConsumption.power, "DateTime:", new Date(powerConsumption.timestamp));
  }
});
smartPlugPowerMonitor.start();
`

But after the wattage has dropped below 1, it does not send a IFTTT push notification. I tried to set it of manually and that works fine. (https://maker.ifttt.com/trigger/{event}/with/key/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)

**Comment by robertvorthman** [comment]
You should not alter the contents of the node_modules folder.

Do you see the wattage number change in the console output when you turn on an appliance plugged into your smart plug?

Try adding an event callback option to debug if smartPlugPowerMonitor is correctly identifying when your appliance starts and stops running.  You should see the ```appliance-started``` and ```appliance-completed``` events logged to the console if you use the code below.  Understand that the ```appliance-completed``` event will not fire until the appliance is below the wattage threshold for 30 seconds, after which the ```appliance-started``` will not fire unless the appliance remains off for at least 30 seconds.  These default durations can be changed by passing different ```endTimeWindowSeconds``` and ```cooldownPeriodSeconds``` options.

```js
var smartPlugPowerMonitor = new SmartPlugPowerMonitor({
smartPlugIP: "192.168.1.23",
iftttMakerChannelKey: "https://maker.ifttt.com/use/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
endEventName: 'appliance-completed',
wattsThreshold: 1,
pollIntervalSeconds: 5,
pollingCallback: function(powerConsumption){
console.log("Wattage:", powerConsumption.power, "DateTime:", new Date(powerConsumption.timestamp));
},
eventCallback: (event, data)=>{
  console.log('Smart plug event', event, data);
}
});
```

**Comment by rgerr** [comment]
`0 1520796584998
0 1520796600119
0 1520796615190
0 1520796630252
0 1520796645311
2.711343 1520796660377
2.540017 1520796675453
2.43767 1520796690596
2.395795 1520796705661
2.495306 1520796720713
2.441033 1520796735757
2.472885 1520796750815
2.388541 1520796765865
2.451914 1520796780909
2.438198 1520796795973
2.45264 1520796811052
2.420194 1520796826110
2.421975 1520796841167
2.363415 1520796856231
2.378319 1520796871292
2.409379 1520796886355
2.372582 1520796901422
2.317254 1520796916472
2.307032 1520796931526
2.41327 1520796946587
2.42059 1520796961643
2.271883 1520796976705
2.374099 1520796991757
2.371329 1520797006817
2.40595 1520797021885
2.299976 1520797037000
2.365592 1520797052048
2.508034 1520797067115
0 1520797082183
0 1520797097242
0 1520797112316
2.424613 1520797142416
2.384122 1520797157477
2.376736 1520797172524
2.312769 1520797187593
2.406808 1520797202654
2.305647 1520797217745
2.378385 1520797232809
2.289755 1520797247856
2.296943 1520797262912
2.205542 1520797277992
2.435032 1520797293067
2.36757 1520797308143
2.331036 1520797323215
2.287776 1520797338280
2.313165 1520797353356
2.366119 1520797368423
`

Turned on the washing machine (wattage is above 1 as you can see).

However, in the log I don't see an 'appliance-started' or 'appliance-completed' message.

Below is the script I am using:

`var SmartPlugPowerMonitor = require("smart-plug-power-monitor");

var smartPlugPowerMonitor = new SmartPlugPowerMonitor({
  smartPlugIP: "192.168.1.xx",
  iftttMakerChannelKey: "https://maker.ifttt.com/use/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  startEventName: 'appliance-started',
  endEventName: 'appliance-completed',
  wattsThreshold: 1,
  pollIntervalSeconds: 15,
  pollingCallback: function(powerConsumption){
    console.log(powerConsumption.power, powerConsumption.timestamp);
  }
});
smartPlugPowerMonitor.start();`

**Comment by rgerr** [comment]
Seeing the event launch, but not receiving a IFTTT message unfortunatly.

Wattage: 2.424415 DateTime: 2018-03-11T19:48:36.612Z
Wattage: 2.283556 DateTime: 2018-03-11T19:48:57.277Z
Smart plug event appliance-started undefined
Wattage: 2.28283 DateTime: 2018-03-11T19:49:02.418Z
Wattage: 2.138674 DateTime: 2018-03-11T19:49:07.459Z
Wattage: 2.260739 DateTime: 2018-03-11T19:49:12.511Z

Wattage: 0 DateTime: 2018-03-11T19:54:26.062Z
Wattage: 0 DateTime: 2018-03-11T19:54:31.115Z
Wattage: 0 DateTime: 2018-03-11T19:54:36.155Z
Smart plug event appliance-completed { runtime: 329164, kwh: 0, cost: 0 }
Wattage: 0 DateTime: 2018-03-11T19:55:06.257Z
Wattage: 0 DateTime: 2018-03-11T19:55:11.308Z
Wattage: 0 DateTime: 2018-03-11T19:55:16.347Z
Wattage: 0 DateTime: 2018-03-11T19:55:21.389Z
Wattage: 0 DateTime: 2018-03-11T19:55:26.433Z
Wattage: 0 DateTime: 2018-03-11T19:55:31.474Z
Wattage: 0 DateTime: 2018-03-11T19:55:36.517Z
Wattage: 0 DateTime: 2018-03-11T19:55:41.575Z
Wattage: 0 DateTime: 2018-03-11T19:55:46.622Z
Wattage: 0 DateTime: 2018-03-11T19:55:51.665Z
Wattage: 0 DateTime: 2018-03-11T19:55:56.708Z
Wattage: 0 DateTime: 2018-03-11T19:56:01.763Z

**Comment by robertvorthman** [comment]
Remove the "https://maker.ifttt.com/use/" from the ```iftttMakerChannelKey``` option.  You should only pass the key, not the full URL of the IFTTT web hooks service.

You can view if IFTTT received an event by looking at https://ifttt.com/activity

**Comment by rgerr** [comment]
Awesome, it’s working now! I changed the IFTTT maker key without https and so forth, and kust received a push massage from ITFFF that the device had started.

Thank you so much for your time and help. And thank you for this great node!

**Comment by robertvorthman** [comment]
You're welcome.  I'm glad people are using this code.  I'd love to hear about what you are doing with the smart plug power monitor.  Just trying to get notified when an appliance is done working?

**Comment by rgerr** [comment]
Currently using it for my washing machine. But the possibilities are endless: phone/tablet charger(s), dishwasher, sprinkler(s), washdryer, etc. Any other suggestions?

**Comment by cldpl** [comment]
Hello,
this works correctly with HS110 using hw_ver: 1.0 and sw_ver: 1.1.4.
Using a new HS110 plug (hw_ver: 2.0 and sw_ver: 1.5.4) the code doesn't work, I get undefined values when polling it.

Is it possible to fix the code in order to work even with new plugs?

Thank you.

**Comment by robertvorthman** [comment]
@cldpl Next time create a new issue instead of replying to an unrelated issue.  This package relies on the hs100-api package, which is 3 years old and has been replaced by tplink-smarthome-api, which being newer, is more likely to support new plugs, though I am not sure.

Try running the example from [https://www.npmjs.com/package/tplink-smarthome-api ](https://www.npmjs.com/package/tplink-smarthome-api )and see if you can build something to alert you when the wattage changes.  

I don't use this library anymore, I use node-red to monitor my smart plugs.
