### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by SolarAngel** [robertvorthman/smart-plug-power-monitor#4]
Tried to reinstall the smart plug power monitor after a fatal RPI3 crash. Unfortunately cannot do this. Error stated below:
pi@raspberrypi:~ $ sudo npm install https://github.com/robertvorthman/smart-plug-power-monitor.gitnpm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/robertvorthman/smart-plug-power-monitor.git /root/.npm/_cacache/tmp/git-clone-1096192e
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-1096192e': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-30T15_15_25_928Z-debug.log

Also tried to install without NPM but to no avail. Node version 8.x

**Comment by robertvorthman** [comment]
Have you tried any npm troubleshooting steps?  Can you install other node packages?

**Comment by SolarAngel** [comment]
Yes, NPM warned me to update to the actual version 6.0.0 so I did. Other node packages can be installed. Now another error shows up
pi@raspberrypi:~ $ sudo npm install https://github.com/robertvorthman/smart-plug-power-monitor.git
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-6442b407': Permission denied
Also tried to install without SUDO but then the well known no permission error appears

**Comment by robertvorthman** [comment]
I can't replicate the issue.  Maybe try cloning the repository and then running "npm install" from within this modules folder?

**Comment by SolarAngel** [comment]
Will do. Thanks for your support so far 👍

**Comment by SolarAngel** [comment]
OK, was able to clone the repository using Github's instructions, but what's next? Tried to install but the following error occurs:
pi@raspberrypi:~/Downloads $ git clone https://github.com/robertvorthman/smart-plug-power-monitor.git
Cloning into 'smart-plug-power-monitor'...
remote: Counting objects: 154, done.
remote: Total 154 (delta 0), reused 0 (delta 0), pack-reused 154
Receiving objects: 100% (154/154), 27.86 KiB | 0 bytes/s, done.
Resolving deltas: 100% (63/63), done.
pi@raspberrypi:~/Downloads $ cd /home/pi/Downloads/smart-plug-power-monitor
pi@raspberrypi:~/Downloads/smart-plug-power-monitor $ npm install smart-plug-power-monitor
npm ERR! code E404
npm ERR! 404 Not Found: smart-plug-power-monitor@latest

npm ERR! A complete log of this run can be found in:

**Comment by robertvorthman** [comment]
Type just ```npm install``` from within the smart-plug-power-monitor folder.  That command installs from a package.json file in the same directory.

**Comment by SolarAngel** [comment]
OK, tried to do so. In the meantime also performed an sudo apt-get update and sudo apt-get upgrade. Some things were updated and some things were upgraded. Also tried to uninstall and reinstall XPC-connection but

unfortunately still no luck, see below:
pi@raspberrypi:~/Downloads $ sudo npm install
npm WARN deprecated undefined@0.1.0: this package has been deprecated
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: arm

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-05T14_03_50_236Z-debug.log
pi@raspberrypi:~/Downloads $

**Comment by robertvorthman** [comment]
You need to run “npm install” from within this modules folder where the smart plug package.json file is. The error is showing that npm is looking for a package.json in /home/pi so that won’t work

**Comment by SolarAngel** [comment]
Ah, that did the trick! Thanks! Now it seems installed. Added an index.js to the newly created node_modules subdirectory but when trying to run node index.js the following occured:

pi@raspberrypi:~/Downloads/smart-plug-power-monitor/node_modules $ node index.jsmodule.js:549
    throw err;
    ^

Error: Cannot find module 'smart-plug-power-monitor'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/Downloads/smart-plug-power-monitor/node_modules/index.js:1:91)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Seems like I am still missing something? 

Many thanks for your support, it used to work and my wife was very happy with it :-)

**Comment by robertvorthman** [comment]
You shouldn't mess with files in the node_modules folder.  I think what you should do is install this module globally so that you can place your .js file anywhere.  Run ```npm install -g``` from the module's directory that has the package.json file.   Then create a folder in your documents for your specific project, and put a .js file there (NOT a node_modules folder, only npm commands should change that directory).

Now you can delete the folder that was created from ```git clone```.

**Comment by SolarAngel** [comment]
OK, did as you indicated, ran SUDO NPM install -G and got the information that 
pi@raspberrypi:~/Downloads/smart-plug-power-monitor $ sudo npm install -g
+ smart-plug-power-monitor@0.1.0
added 1 package from 1 contributor in 2.571s
 
Afterwards I created a new directory : /home/pi/SPPM/ and put the index.js file in there. Afterwards tried to run index.js from there but still the same error message occurs. 

pi@raspberrypi:~/SPPM $ node index.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'smart-plug-power-monitor'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/SPPM/index.js:1:91)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Maybe I should just reinstall everything and start from scratch? Don't understand why it's not working anymore. It used to.

**Comment by robertvorthman** [comment]
Since the module is installed under the sudo user, make sure you run your custom script as the sudo user too, like ```sudo node index.js```

**Comment by SolarAngel** [comment]
An update after some time: started again from scratch, followed the same steps but this time it's working again 👍 

Thanks for your support! :)
