### ISSUE TITLE
Run two instances with two plugs

### ISSUE THREAD

**Issue by rgerr** [robertvorthman/smart-plug-power-monitor#6]
How can I run two instances at the same time, for two plugs, while still receiving the correct IFTTT message? Since both scripts fire ‘appliance-started’ and ‘appliance-completed’, I would receive the same message if one of the devices goes below the treshhold.

**Comment by robertvorthman** [comment]
You can customize the IFTTT event names for each instance of SmartPlugPowerMonitor

```js

const appliance1 = new SmartPlugPowerMonitor({
  smartPlugIP: "192.168.5.51",
  startEventName: 'appliance1-started',
  endEventName: 'appliance1-completed'
});
appliance1.start()

const appliance2 = new SmartPlugPowerMonitor({
  smartPlugIP: "192.168.5.52",
  startEventName: 'appliance2-started',
  endEventName: 'appliance2-completed'
});
appliance2.start()

```
